baseURL = "http://laziz3.netlify.com"
disableLanguages = ["FR"]
disqusShortname = "Laziz"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "Data Science Portfolio"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 1
[[Languages.en.menu.main]]
name = "Certifications"
url = "course"
weight = 2
[[Languages.en.menu.main]]
name = "Projects"
url = "blog"
weight = 3
[[Languages.en.menu.main]]
name = "LINKEDIN"
url = "https://www.linkedin.com/in/laziz-yuldoshev-870280ab/"
weight = 5
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
name = "teacher"
url = "teacher"
[[Languages.fr.menu.footer]]
name = "notice"
url = "notice"
[[Languages.fr.menu.footer]]
name = "event"
url = "event"
[[Languages.fr.menu.footer]]
name = "scholarship"
url = "scholarship"
[[Languages.fr.menu.footer]]
name = "research"
url = "research"
[[Languages.fr.menu.main]]
name = "À propos"
url = "about"
weight = 1
[[Languages.fr.menu.main]]
name = "Cours"
url = "course"
weight = 2
[[Languages.fr.menu.main]]
hasChildren = true
name = "Pages"
weight = 3
[[Languages.fr.menu.main]]
name = "teacher"
parent = "Pages"
url = "teacher"
[[Languages.fr.menu.main]]
name = "notice"
parent = "Pages"
url = "notice"
[[Languages.fr.menu.main]]
name = "Évènement"
parent = "Pages"
url = "event"
[[Languages.fr.menu.main]]
name = "Cursus"
parent = "Pages"
url = "scholarship"
[[Languages.fr.menu.main]]
name = "research"
parent = "Pages"
url = "research"
[[Languages.fr.menu.main]]
name = "blog"
url = "blog"
weight = 4
[[Languages.fr.menu.main]]
name = "Contact"
url = "contact"
weight = 5
[params]
address = "ayuldosh@uncc.edu"
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
email = "(917) 371 32 40"
google_analitycs_id = ""
logo = "images/logo.png"
top_header = false
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[params.subscription]
enable = false
[[params.social]]
[[params.social]]
[[params.social]]
[[params.social]]
icon = "ti-github"
link = "https://github.com/Laziz10"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/laziz-yuldoshev-870280ab/"
title = "linkedin"
